unifi_controllers:
  - name: main
    controller_url: "https://unifi.example.com:8443"
    username: your_local_admin_user
    password: your_password
    is_udm_pro: false
    verify_ssl: true
    # api_version: v5  # Optional: specify API version (auto-detected if omitted)
  
  - name: remote
    controller_url: "https://remote.example.com:443"
    username: admin
    password: your_password
    is_udm_pro: true
    verify_ssl: false
    api_version: unifiOS  # Optional: force specific API version for UDM Pro

unifi_timezone: America/New_York
unifi_schedule_time: "02:00"
unifi_output_dir: /output
output_format: markdown

# Feature toggles
include_networks: true
include_wifi_networks: true  
include_devices: true
include_clients: true
include_firewall_rules: true
include_nat_rules: true
include_settings: true
include_ip_addressing: true