#!/bin/bash
set -e

# Set timezone if provided
if [ -n "$TZ" ]; then
    echo "Setting timezone to $TZ"
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
    echo $TZ > /etc/timezone
fi

# Configuration validation
if [ -z "$UNIFI_HOST" ]; then
    echo "ERROR: UNIFI_HOST environment variable is required"
    exit 1
fi

if [ -z "$UNIFI_SSH_USER" ]; then
    echo "ERROR: UNIFI_SSH_USER environment variable is required"
    exit 1
fi

if [ -z "$UNIFI_SSH_PASSWORD" ] && [ -z "$UNIFI_SSH_KEY" ]; then
    echo "ERROR: Either UNIFI_SSH_PASSWORD or UNIFI_SSH_KEY must be provided"
    exit 1
fi

# Set default values
BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-"0 2 * * *"}  # Daily at 2 AM by default
BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-30}
RUN_ONCE=${RUN_ONCE:-false}

echo "UniFi Documenter starting..."
echo "Host: $UNIFI_HOST"
echo "User: $UNIFI_SSH_USER"
echo "Schedule: $BACKUP_SCHEDULE"
echo "Retention: $BACKUP_RETENTION_DAYS days"
echo "Run once: $RUN_ONCE"

# Setup SSH key if provided
if [ -n "$UNIFI_SSH_KEY" ]; then
    echo "Setting up SSH key authentication..."
    mkdir -p ~/.ssh
    echo "$UNIFI_SSH_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    chmod 700 ~/.ssh
    
    # Add host to known_hosts to avoid interactive prompts
    ssh-keyscan -H "$UNIFI_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
fi

# Initialize Git repository in backups directory
cd /backups
if [ ! -d ".git" ]; then
    echo "Initializing Git repository for backup versioning..."
    git init
    git config user.name "UniFi Documenter"
    git config user.email "unifi-documenter@localhost"
    
    # Create initial commit
    echo "# UniFi Network Documentation" > README.md
    echo "" >> README.md
    echo "This repository contains automated backups and documentation" >> README.md
    echo "of UniFi network configuration." >> README.md
    echo "" >> README.md
    echo "Generated by UniFi Documenter on $(date)" >> README.md
    
    git add README.md
    git commit -m "Initial commit - UniFi Documenter setup"
fi

# Function to run backup
run_backup() {
    echo "$(date): Starting backup process..."
    cd /app
    
    if python3 backup.py; then
        echo "$(date): Backup completed successfully"
    else
        echo "$(date): Backup failed"
        return 1
    fi
}

# Function to setup cron job
setup_cron() {
    echo "Setting up cron job with schedule: $BACKUP_SCHEDULE"
    
    # Create cron entry
    echo "$BACKUP_SCHEDULE cd /app && python3 backup.py >> /app/logs/cron.log 2>&1" > /tmp/crontab
    
    # Install cron job
    crontab /tmp/crontab
    
    # Start cron daemon
    echo "Starting cron daemon..."
    cron
    
    echo "Cron job installed and daemon started"
}

# Handle different run modes
if [ "$RUN_ONCE" = "true" ]; then
    echo "Running backup once and exiting..."
    run_backup
    exit $?
else
    echo "Setting up scheduled backups..."
    
    # Run initial backup
    echo "Running initial backup..."
    run_backup || echo "Initial backup failed, but continuing with scheduler..."
    
    # Setup cron
    setup_cron
    
    # Keep container running and show logs
    echo "Container is running. Monitoring logs..."
    echo "Press Ctrl+C to stop"
    
    # Create log monitoring loop
    touch /app/logs/cron.log
    tail -f /app/logs/backup.log /app/logs/cron.log &
    
    # Wait for signals
    trap 'echo "Shutting down..."; kill %1; exit 0' SIGTERM SIGINT
    
    # Keep the container alive
    while true; do
        sleep 60
        # Check if cron is still running
        if ! pgrep cron > /dev/null; then
            echo "Cron daemon stopped, restarting..."
            cron
        fi
    done
fi